name: nuttx

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cool
      run: |
        sudo apt-get -y install make
        sudo apt-get install git gperf libncurses5-dev flex bison gcc-arm-none-eabi
        sudo apt-get install kconfig-frontends
        git clone --recursive https://github.com/sonydevworld/spresense.git
        cd spresense/sdk
        tools/config.py examples/hello
        make
